name: Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
    - name: LS
      working-directory: ./poligon_playwright
      run:  ls
    - name: Install dependencies
      working-directory: ./poligon_playwright
      run: npm ci
    - name: Install Playwright Browsers
      working-directory: ./poligon_playwright
      run: npx playwright install --with-deps
    - name: Run Playwright tests
      working-directory: ./poligon_playwright
      run: npx playwright test
    - uses: actions/upload-artifact@v4
      if: always()
      with:
        name: playwright-report
        path: ./poligon_playwright/playwright-report/
        retention-days: 30
